from python
#run apt install vim
env db_user=""
env db_pass=""
env db_address="" 
env db = "" 
run pip install mysql-connector-python
workdir /apps/con/
add con.py con.py 
cmd python /apps/con/con.py
