apiVersion: batch/v1
kind: CronJob 
metadata:
  name: cronanalise
spec: 
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec: 
      template:
        spec: 
          containers: 
          - name: con
            image: essantos70/emsantos70:v1_job
            env:
              - name: db_address
                valueFrom: 
                  configMapKeyRef: 
                    name: configmapgeneral
                    key: db_address
              - name: pass
                valueFrom: 
                  secretKeyRef:
                    name: db-user-pass 
                    key: pass
            envFrom:
              - configMapRef:
                  name: cronconfigmap 
            imagePullPolicy: IfNotPresent
              #concurrencyPolicy: Forbid
          restartPolicy: Never #OnFailure
