apiVersion: v1
kind: Service
metadata:
  name:  mysql-svc
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector: 
    app: mysql
  clusterIP: 10.104.233.100
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmysql
data:
  MYSQL_ROOT_PASSWORD: passwordRoot
  MYSQL_USER: lab
  MYSQL_PASSWORD: passwordRoot
  MYSQL_DATABASE: mimosa
  MYSQL_ROOT_HOST: '%'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: database-volume
        ports:
          - containerPort: 3306
          - containerPort: 33060
        env: 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              configMapKeyRef:
                name: configmysql
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: configmysql
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: configmysql
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: configmysql
                key: MYSQL_DATABASE
          - name: MYSQL_ROOT_HOST
            valueFrom:
              configMapKeyRef:
                name: configmysql
                key: MYSQL_ROOT_HOST           
            #envFrom:
            # configMapKeyRef:
            #name: configmysql
            #key: MYSQL_ROOT_PASSWORD
          #- configMapRef:
          #  name: configmysql
      volumes:
      - name: database-volume
        hostPath:
          path: /mimosaDatabase
          type: DirectoryOrCreate
  selector:
    matchLabels:
      app: mysql

