apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
spec: 
  replicas: 1 
  template: 
    metadata:
      name: backend 
      labels:
        app: backend
    spec: 
      containers:
      - name: backend
        image: essantos70/emsantos70:back_v2
        env:
          - name: db_address
            valueFrom:
              configMapKeyRef:
                name: configmapgeneral
                key: db_address
          - name: pass
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: pass
        envFrom:
          - configMapRef:
              name: confimapbackend
        volumeMounts:
          - mountPath: /dataset/
            name: dataset
        ports: 
          - containerPort: 80
        resources:
          requests:
            memory: "200Mi"
            cpu: "40m"
          limits:
            memory: "300Mi"
            cpu: "100m"
      volumes:
      - name: dataset
        hostPath: 
          path: /dataset/
          type: DirectoryOrCreate 
  selector:
    matchLabels:
      app: backend  
