apiVersion: v1
kind: Service
metadata:
  name: backservice
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 7777
      targetPort: 7777
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30008
