apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: lab.com.br.teste
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontservice
            port:
              number: 80
      - path: /retry
        pathType: Prefix 
        backend:
          service: 
            name: backservice 
            port:
              number: 7777

