apiVersion: v1
kind: Service
metadata: 
  name: nginx-clusterip
spec:
  selector: 
    app: my-clusterip
  type: ClusterIP
  ports: 
    - name: http
      port: 7777
      targetPort: 80
      protocol: TCP 
