apiVersion: batch/v1
kind: CronJob 
metadata:
  name: conecta
spec: 
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec: 
      template:
        spec: 
          containers: 
          - name: conecta
            image: essantos70/emsantos70:v1_conecta
            env:
              - name: db_address
                valueFrom:
                  configMapKeyRef:
                    name: configmapgeneral
                    key: db_address
              - name: pass
                valueFrom: 
                  secretKeyRef:
                    name: db-user-pass
                    key: pass
            envFrom: 
              - configMapRef:
                  name: configmapconecta 
            volumeMounts:
              - mountPath: /tmp/
                name: volume
          volumes: 
          - name: volume
            hostPath: 
              path: /volume/
              type: DirectoryOrCreate
          restartPolicy: OnFailure
